apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logstash-test
spec:
  replicas: 3
  revisionHistoryLimit: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: logstash-test
    spec:
      hostNetwork: true
      containers:
        - name: logstash-test
          image: docker.example.com/organization/logstash-test
          imagePullPolicy: Always
